apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-transferencia-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-transferencia
  template:
    metadata:
      labels:
        app: api-transferencia
    spec:
      containers:
        - name: api-transferencia
          image: api-transferencia:v1
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: api-transferencia-service
spec:
  selector:
    app: api-transferencia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer