spring:
  application:
    name: api-transferencia
  main:
    allow-bean-definition-overriding: true
server:
  port: 8083
  servlet:
    context-path: /api-transferencia

management:
  endpoints.web:.exposure.include: "*"
  endpoint.health:.show-details: ALWAYS
  health:
    diskspace: false
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests:  true
        resilience4j.circuitbreaker.calls: true

resilience4j:
  circuitbreaker:
    backendA:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 20
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 60000
      failureRateThreshold: 20
      eventConsumerBufferSize: 10
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: true
        exponential-max-wait-duration:
          seconds: 2
    instances:
      backendA:
        baseConfig: default

properties:
  rest:
    api:
      cadastro:
        url: http://localhost:9090/clientes
      contas:
        url: http://localhost:9090/contas
      bacen:
        url: http://localhost:9090/notificacoes

springdoc:
  swagger-ui:
    path: /documentacao

aws:
  sqs:
  url: http://localhost:4566/000000000000/myQueue

  #docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 -e LOCALSTACK_AUTH_TOKEN="ls-JoKo2234-ZOzA-LOmO-LeJi-FEXetaDIff18" localstack/localstack-pro
  #aws ecr get-login-password --region us-east-1 --endpoint-url=http://localhost:4566 | docker login --username AWS --password-stdin localhost:4566